### PR TITLE
Change color

### PR DESCRIPTION
**Pull request by sjy5386**
like dark mode

We love dark mode theme.

and change default font (sans-serif).

I don't know change JSplitPane's and JScrollPane's color.
If you like dark mode, you should resolve this.

### CODE REVIEW

**Comment by Kasania** [comment]
That is reasonable, but UIManager's values must not changed.    
We have to create global color and theme element, like [Android](https://developer.android.com/guide/topics/ui/look-and-feel/themes)

**Comment by sjy5386** [comment]
Please make a theme template.

**Comment by sjy5386** [comment]
light mode theme

**Comment by sjy5386** [comment]
mspaint style theme

**Comment by sjy5386** [comment]
youtube style theme

**Comment by Kasania** [comment]
I will add theme system, this pull request will be converted to issue.

**Pull request closed without merging**
